version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres-container
    networks:
      - saude-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: oli_saude_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:7.9.0
    container_name: flyway-container
    command: [ "-url=jdbc:postgresql://database:5432/oli_saude_db", "-user=admin", "-password=mypassword", "migrate" ]
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - database
    networks:
      - saude-network

  oli-saude:
    build: .
    image: oli-saude
    container_name: oli-saude
    networks:
      - saude-network
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/oli_saude_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=mypassword

networks:
  saude-network:
      driver: bridge

volumes:
  postgres-data:
    driver: local